// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type AiInvocation struct {
	ID             int64
	Command        string
	Model          string
	PromptLength   sql.NullInt64
	ResponseLength sql.NullInt64
	LatencyMs      sql.NullInt64
	Success        int64
	Error          sql.NullString
	CreatedAt      sql.NullTime
}

type CommandExecution struct {
	ID          int64
	Command     string
	CommandType string
	DurationMs  int64
	ExitCode    int64
	Flags       sql.NullString
	ExecutedAt  sql.NullTime
}
